print("Welcome to hello.py")
print("___________________")
print()
print()
print("Hello User, I would like to know your name.")
userName = input("Please Enter your name: ")
print()
print("Why hello " + userName + "! My name is Dylan DogBot. I will be delighted to help you with your math homework.")
print()
print("Let's do some addition: ")
x = int(input("Please enter your first number whole number: "))
y = int(input("Thank you, please enter your second whole number: "))
print()
print("Thank you, here is your equation: ")
print("  ", x)
print("  ", y)
print("+______")
result = x+y
print("  ", result) 
